=== LineVA/zoo/zoo/resources/species/specie.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="animal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="names">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="fr"/>
                            <xs:element name="additionalFrenchNames">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="en"/>
                            <xs:element name="additionalEnglishNames">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="scientific"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="general">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="uicn"/>
                            <xs:element type="xs:string" name="family"/>
                            <xs:element name="continents">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="continent" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:integer" name="ecoregion"/>
                            <xs:element type="xs:string" name="breedingProgramme"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="documentation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="frenchWikipedia"/>
                            <xs:element type="xs:string" name="englishWikipedia"/>
                            <xs:element type="xs:string" name="animalDiversity"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="reproduction">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="femaleMaturity"/>
                            <xs:element type="xs:integer" name="maleMaturity"/>
                            <xs:element type="xs:decimal" name="gestationFrequency"/>
                            <xs:element type="xs:integer" name="gestationDuration" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:integer" name="litterSize"/>
                            <xs:element type="xs:integer" name="weaningAge" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:integer" name="leavingAge" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lifespan">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="femaleLifespan"/>
                            <xs:element type="xs:decimal" name="maleLifespan"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="territory">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="territorySize"/>
                            <xs:element name="biomes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="biome" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="feeding">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="quantity"/>
                            <xs:element type="xs:int" name="size"/>
                            <xs:element name="diets">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="diet" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:int" name="fastDays" maxOccurs="1" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="social">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="groupSize"/>
                            <xs:element type="xs:string" name="territorial" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="activityPeriods" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="period" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="socialStructures" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="structure" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="maleParticipationInBreeding" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="isolationOfYoung" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tags" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="frenchTags">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="tag" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="englishTags">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="tag" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LineVA/zoo/zoo/resources/species/northernWhiteCheekedGibbon.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Gibbon à joues pâles</fr>
    <additionalFrenchNames>
        <name>Gibbon à joues blanches</name>
        <name>Gibbon à favoris blancs du Nord</name>
    </additionalFrenchNames>
    <en>Northern white-cheeked gibbon</en>
    <additionalEnglishNames>
    </additionalEnglishNames>
    <scientific>Nomascus leucogenys leucogenys</scientific>
  </names>
  <general>
    <uicn>5</uicn>
    <family>30</family>
    <continents>
      <continent>5</continent>
    </continents>
    <ecoregion>0</ecoregion>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Nomascus_leucogenys</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Northern_white-cheeked_gibbon</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>84</femaleMaturity>
    <maleMaturity>84</maleMaturity>
    <gestationFrequency>0.4</gestationFrequency>
    <litterSize>1</litterSize>
    <leavingAge>72</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>336</femaleLifespan>
    <maleLifespan>336</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>100</territorySize>
    <biomes>
      <biome>2</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>1.042</quantity>
    <size>2</size>
    <diets>
      <diet>5</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>2</groupSize>
  </social>
</animal>

=== LineVA/zoo/zoo/resources/species/lot1/cokesHartebeest.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Bubale kongoni</fr>
        <additionalFrenchNames>
        </additionalFrenchNames>
        <en>Coke's hartebeest</en>
        <additionalEnglishNames>
            <name>Kongoni</name>
        </additionalEnglishNames>
        <scientific>Alcelaphus buselaphus cokii</scientific>
    </names>
    <general>
        <uicn>1</uicn>
        <family>19</family>
        <continents>
            <continent>1</continent>
        </continents>
        <ecoregion>0</ecoregion>
        <breedingProgramme>0</breedingProgramme>
    </general>
    <documentation>
        <frenchWikipedia>https://fr.wikipedia.org/wiki/Alcelaphus_buselaphus</frenchWikipedia>
        <englishWikipedia>https://en.wikipedia.org/wiki/Coke's_hartebeest</englishWikipedia>
        <animalDiversity />
    </documentation>
    <reproduction>
        <femaleMaturity>36</femaleMaturity>
        <maleMaturity>36</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <gestationDuration>8</gestationDuration>
        <litterSize>1</litterSize>
        <weaningAge>4</weaningAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>180</femaleLifespan>
        <maleLifespan>180</maleLifespan>
    </lifespan>
    <territory>
        <territorySize>2200</territorySize>
        <biomes>
            <biome>7</biome>
        </biomes>
    </territory>
    <feeding>
        <quantity>3.6</quantity>
        <size>6</size>
        <diets>
            <diet>8</diet>
        </diets>
    </feeding>
    <social>
        <groupSize>10</groupSize>
    </social>
    <tags>
        <frenchTags>
            <tag>Mammifère</tag>
            <tag>Bovidé</tag>
            <tag>Antilope</tag>
            <tag>Alcelaphinae</tag>
            <tag>Hartebeest</tag>
            <tag>Bubale</tag>
            <tag>Kongoni</tag>
        </frenchTags>
        <englishTags>
            <tag>Mammal</tag>
            <tag>Kob</tag>
            <tag>Bovine</tag>
            <tag>Antelope</tag>
            <tag>Alcelaphinae</tag>
            <tag>Hartebeest</tag>
            <tag>Coke</tag>
        </englishTags>
    </tags>
</animal>

=== LineVA/zoo/zoo/resources/species/lot1/westernGorilla.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Gorille de l'Ouest</fr>
        <additionalFrenchNames>
        </additionalFrenchNames>
        <en>Western gorilla</en>
        <additionalEnglishNames>
        </additionalEnglishNames>
        <scientific>Gorilla gorilla</scientific>
    </names>
    <general>
        <uicn>5</uicn>
        <family>36</family>
        <continents>
            <continent>1</continent>
        </continents>
        <ecoregion>0</ecoregion>
        <breedingProgramme>1</breedingProgramme>
    </general>
    <documentation>
        <frenchWikipedia>https://fr.wikipedia.org/wiki/Gorille_de_l'Ouest</frenchWikipedia>
        <englishWikipedia>https://en.wikipedia.org/wiki/Western_gorilla</englishWikipedia>
        <animalDiversity />
    </documentation>
    <reproduction>
        <femaleMaturity>120</femaleMaturity>
        <maleMaturity>180</maleMaturity>
        <gestationFrequency>0.25</gestationFrequency>
        <gestationDuration>9</gestationDuration>
        <litterSize>1</litterSize>
        <weaningAge>42</weaningAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>410</femaleLifespan>
        <maleLifespan>410</maleLifespan>
    </lifespan>
    <territory>
        <territorySize>600</territorySize>
        <biomes>
            <biome>1</biome>
        </biomes>
    </territory>
    <feeding>
        <quantity>5.6</quantity>
        <size>7</size>
        <diets>
            <diet>21</diet>
        </diets>
    </feeding>
    <social>
        <groupSize>7</groupSize>
    </social>
    <tags>
        <frenchTags>
            <tag>Mammif√®re</tag>
            <tag>Primate</tag>
            <tag>Singe</tag>
            <tag>Gorille</tag>
            <tag>Ouest</tag>
        </frenchTags>
        <englishTags>
            <tag>Mammal</tag>
            <tag>Primate</tag>
            <tag>Monkey</tag>
            <tag>Gorilla</tag>
            <tag>Western</tag>
            <tag>West</tag>
        </englishTags>
    </tags>
</animal>

=== LineVA/zoo/zoo/resources/species/vervetMonkey.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Grivet</fr>
    <additionalFrenchNames>
      <name>Singe vert</name>
      <name>Grivet d'Ethiopie</name>
    </additionalFrenchNames>
    <en>Vervet</en>
    <additionalEnglishNames>
      <name>Vervet monkey</name>
      <name>Grivet</name>
      <name>Green monkey</name>
    </additionalEnglishNames>
    <scientific>Chlorocebus pygerythrus</scientific>
  </names>
  <general>
    <uicn>1</uicn>
    <family>31</family>
    <continents>
      <continent>1</continent>
    </continents>
    <ecoregion>0</ecoregion>
    <breedingProgramme>0</breedingProgramme>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Chlorocebus_aethiops</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Vervet_monkey</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>36</femaleMaturity>
    <maleMaturity>72</maleMaturity>
    <gestationFrequency>0.5</gestationFrequency>
    <litterSize>1</litterSize>
    <leavingAge>0</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>360</femaleLifespan>
    <maleLifespan>360</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>40</territorySize>
    <biomes>
      <biome>7</biome>
    </biomes>
  </territory>
 <feeding>
    <quantity>0.772</quantity>
    <size>2</size>
    <diets>
      <diet>17</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>5</groupSize>
  </social>
  <tags>
      <frenchTags>
          <tag>Mammif√®re</tag>
          <tag>Primate</tag>
      </frenchTags>
      <englishTags>
          <tag>Mammal</tag>
          <tag>Primate</tag>
          <tag>Monkey</tag>
      </englishTags>
  </tags>
</animal>

=== LineVA/zoo/zoo/resources/tmpSpecies/ringTailedLemur.xml
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./specie.xsd">
    <names>
        <fr>Maki catta</fr>
        <en>Ring-tailed lemur</en>
        <scientific>Lemur catta</scientific>
    </names>
    <reproduction>
        <femaleMaturity>36</femaleMaturity>
        <maleMaturity>42</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>1</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>324</femaleLifespan>
        <maleLifeSpan>324</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/resources/species/pumaConcolor.xml
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./specie.xsd">
    <names>
        <fr>Puma</fr>
        <en>Cougar</en>
        <scientific>Puma concolor</scientific>
    </names>
<general>
    <uicn>1</uicn>
    <family>Felidae</family>
</general>
<reproduction>
        <femaleMaturity>24</femaleMaturity>
        <maleMaturity>30</maleMaturity>
        <gestationFrequency>0.5</gestationFrequency>
        <litterSize>3</litterSize>
        <leavingAge>12</leavingAge>
</reproduction>
<lifespan>
        <femaleLifespan>228</femaleLifespan>
        <maleLifeSpan>228</maleLifeSpan>
</lifespan>
<territory>
    <biome>1</biome>
    <territorySize>175</territorySize>
</territory>
<feeding>
        <diet>2</diet>
        <quantity>1</quantity>
    </feeding>
<social>
    <groupSize>1</groupSize>
</social>
</animal>

=== LineVA/zoo/zoo/resources/species/lot1/leontopithecusChrysomelas.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Tamarin lion à tête dorée</fr>
    <additionalFrenchNames>
      <name>Singe-lion à tête dorée</name>
    </additionalFrenchNames>
    <en>Golden-headed lion tamarin</en>
    <additionalEnglishNames>
      <name>Golden-headed tamarin</name>
    </additionalEnglishNames>
    <scientific>Leontopithecus chrysomelas</scientific>
  </names>
  <general>
    <uicn>4</uicn>
    <family>26</family>
    <continents>
      <continent>2</continent>
    </continents>
    <ecoregion>0</ecoregion>
    <breedingProgramme>1</breedingProgramme>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Tamarin_lion_%C3%A0_t%C3%AAte_dor%C3%A9e</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Golden-headed_lion_tamarin</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>18</femaleMaturity>
    <maleMaturity>24</maleMaturity>
    <gestationFrequency>1</gestationFrequency>
    <litterSize>2</litterSize>
    <leavingAge>0</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>216</femaleLifespan>
    <maleLifespan>216</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>12</territorySize>
    <biomes>
      <biome>1</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>0.148</quantity>
    <size>1</size>
    <diets>
      <diet>17</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>4</groupSize>
  </social>
    <tags>
        <frenchTags>
            <tag>Mammifère</tag>
            <tag>Primate</tag>
            <tag>Singe</tag>
            <tag>Tamarin</tag>
            <tag>Lion</tag>
            <tag>Tête</tag>
            <tag>Or</tag>
            <tag>Doré</tag>
            <tag>Dorée</tag>
        </frenchTags>
        <englishTags>
            <tag>Mammal</tag>
            <tag>Primate</tag>
            <tag>Monkey</tag>
            <tag>Gold</tag>
            <tag>Golden</tag>
            <tag>Head</tag>
            <tag>Headed</tag>
            <tag>Tamarin</tag>
            <tag>Lion</tag>
        </englishTags>
    </tags>
</animal>

=== LineVA/zoo/zoo_1/resources/atmp/backUpSpecies/leopard.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Léopard</fr>
    <additionalFrenchNames>
      <name>Panthère</name>
    </additionalFrenchNames>
    <en>Leopard</en>
    <additionalEnglishNames>
      <name>Panther</name>
    </additionalEnglishNames>
    <scientific>Panthera pardus</scientific>
  </names>
  <general>
    <uicn>3</uicn>
    <family>8</family>
    <continents>
      <continent>1</continent>
      <continent>5</continent>
    </continents>
    <ecoregion>0</ecoregion>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/L%C3%A9opard</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Leopard</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>31</femaleMaturity>
    <maleMaturity>25</maleMaturity>
    <gestationFrequency>0.5</gestationFrequency>
    <litterSize>2</litterSize>
    <leavingAge>0</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>132</femaleLifespan>
    <maleLifespan>132</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>150</territorySize>
    <biomes>
      <biome>13</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>1.4</quantity>
    <size>4</size>
    <diets>
      <diet>3</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>1</groupSize>
  </social>
</animal>
