=== LineVA/zoo/zoo/resources/species/specie.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="animal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="names">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="fr"/>
                            <xs:element name="additionalFrenchNames">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="en"/>
                            <xs:element name="additionalEnglishNames">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="scientific"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="general">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="uicn"/>
                            <xs:element type="xs:string" name="family"/>
                            <xs:element name="continents">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="continent" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:integer" name="ecoregion"/>
                            <xs:element type="xs:string" name="breedingProgramme"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="documentation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="frenchWikipedia"/>
                            <xs:element type="xs:string" name="englishWikipedia"/>
                            <xs:element type="xs:string" name="animalDiversity"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="reproduction">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="femaleMaturity"/>
                            <xs:element type="xs:integer" name="maleMaturity"/>
                            <xs:element type="xs:decimal" name="gestationFrequency"/>
                            <xs:element type="xs:integer" name="gestationDuration" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:integer" name="litterSize"/>
                            <xs:element type="xs:integer" name="weaningAge" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:integer" name="leavingAge" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lifespan">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="femaleLifespan"/>
                            <xs:element type="xs:decimal" name="maleLifespan"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="territory">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="territorySize"/>
                            <xs:element name="biomes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="biome" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="feeding">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="quantity"/>
                            <xs:element type="xs:int" name="size"/>
                            <xs:element name="diets">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="diet" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:int" name="fastDays" maxOccurs="1" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="social">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="groupSize"/>
                            <xs:element type="xs:string" name="territorial" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="activityPeriods" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="period" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="socialStructures" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="structure" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="maleParticipationInBreeding" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="isolationOfYoung" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tags" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="frenchTags">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="tag" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="englishTags">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="tag" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LineVA/zoo/zoo/resources/species/jaguar.xml
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Jaguar</fr>
        <en>Jaguar</en>
        <scientific>Panthera onca</scientific>
    </names>
    <general>
        <uicn>2</uicn>
        <family>8</family>
        <continents>
            <continent>2</continent>
        </continents>
        <ecoregion>0</ecoregion>
    </general>
    <reproduction>
        <femaleMaturity>30</femaleMaturity>
        <maleMaturity>42</maleMaturity>
        <gestationFrequency>0.5</gestationFrequency>
        <litterSize>3</litterSize>
        <leavingAge>0</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>162</femaleLifespan>
        <maleLifespan>162</maleLifespan>
    </lifespan>
    <territory>
        <biome>1</biome>
        <territorySize>150</territorySize>
    </territory>
    <feeding>
        <diet>3</diet>
        <quantity>4.2</quantity>
        <size>5</size>
    </feeding>
    <social>
        <groupSize>1</groupSize>
    </social>
</animal>

=== LineVA/zoo/zoo/resources/species/allensSwampMonkey.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>NULL</fr>
    <additionalFrenchNames />
    <en>Diana monkey</en>
    <additionalEnglishNames>
    </additionalEnglishNames>
    <scientific>Cercopithecus nigroviridis</scientific>
  </names>
  <general>
    <uicn>3</uicn>
    <family>31</family>
    <continents>
      <continent>1</continent>
    </continents>
    <ecoregion>0</ecoregion>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Cercopith√®que_diane</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Diana_monkey</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>36</femaleMaturity>
    <maleMaturity>36</maleMaturity>
    <gestationFrequency>1</gestationFrequency>
    <litterSize>1</litterSize>
    <leavingAge>6</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>240</femaleLifespan>
    <maleLifespan>240</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>120</territorySize>
    <biomes>
      <biome>1</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>0.603</quantity>
    <size>1</size>
    <diets>
      <diet>17</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>15</groupSize>
  </social>
</animal>

=== LineVA/zoo/zoo/resources/species/bushDog.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Chien des buissons</fr>
        <additionalFrenchNames>
            <name>Chien-bois</name>
        </additionalFrenchNames>
        <en>Bush dog</en>
        <additionalEnglishNames>
        </additionalEnglishNames>
        <scientific>Speothos venaticus</scientific>
    </names>
    <general>
        <uicn>2</uicn>
        <family>1</family>
        <continents>
            <continent>2</continent>
        </continents>
        <ecoregion>0</ecoregion>
        <breedingProgramme>1</breedingProgramme>
    </general>
    <documentation>
        <frenchWikipedia>https://fr.wikipedia.org/wiki/Chien_des_buissons</frenchWikipedia>
        <englishWikipedia>https://en.wikipedia.org/wiki/Bush_dog</englishWikipedia>
        <animalDiversity />
    </documentation>
    <reproduction>
        <femaleMaturity>12</femaleMaturity>
        <maleMaturity>12</maleMaturity>
        <gestationFrequency>1.33</gestationFrequency>
        <litterSize>4</litterSize>
        <leavingAge>0</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>120</femaleLifespan>
        <maleLifespan>120</maleLifespan>
    </lifespan>
    <territory>
        <territorySize>260</territorySize>
        <biomes>
            <biome>1</biome>
            <biome>2</biome>
        </biomes>
    </territory>
    <feeding>
        <quantity>0.3</quantity>
        <size>2</size>
        <diets>
            <diet>3</diet>
        </diets>
    </feeding>
    <social>
        <groupSize>10</groupSize>
    </social>
</animal>

=== LineVA/zoo/zoo/resources/species/lot1/borneanOrangutan.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Orang-outan de Bornéo</fr>
        <additionalFrenchNames>
            <name>Orang-outang de Bornéo</name>
        </additionalFrenchNames>
        <en>Bornean orangutan</en>
        <additionalEnglishNames>
        </additionalEnglishNames>
        <scientific>Pongo pygmaeus</scientific>
    </names>
    <general>
        <uicn>5</uicn>
        <family>36</family>
        <continents>
            <continent>5</continent>
        </continents>
        <ecoregion>0</ecoregion>
        <breedingProgramme>1</breedingProgramme>
    </general>
    <documentation>
        <frenchWikipedia>https://fr.wikipedia.org/wiki/Orang-outon_de_Bornéo </frenchWikipedia>
        <englishWikipedia>https://en.wikipedia.org/wiki/Bornean_orangutan</englishWikipedia>
        <animalDiversity />
    </documentation>
    <reproduction>
        <femaleMaturity>102</femaleMaturity>
        <maleMaturity>138</maleMaturity>
        <gestationFrequency>0.125</gestationFrequency>
        <gestationDuration>8</gestationDuration>
        <litterSize>1</litterSize>
        <weaningAge>50</weaningAge>
        <leavingAge>80</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>510</femaleLifespan>
        <maleLifespan>510</maleLifespan>
    </lifespan>
    <territory>
        <territorySize>140</territorySize>
        <biomes>
            <biome>1</biome>
        </biomes>
    </territory>
    <feeding>
        <quantity>3.0</quantity>
        <size>5</size>
        <diets>
            <diet>5</diet>
        </diets>
    </feeding>
    <social>
        <groupSize>3</groupSize>
    </social>
    <tags>
        <frenchTags>
            <tag>Mammifère</tag>
            <tag>Primate</tag>
            <tag>Singe</tag>
            <tag>Bornéo</tag>
            <tag>Orang</tag>
            <tag>Outan</tag>
            <tag>Orang-outan</tag>
            <tag>Outang</tag>
            <tag>Orang-outang</tag>
        </frenchTags>
        <englishTags>
            <tag>Mammal</tag>
            <tag>Primate</tag>
            <tag>Monkey</tag>
            <tag>Gorilla</tag>
            <tag>Western</tag>
            <tag>West</tag>
            <tag>Bornean</tag>
            <tag>Orangutan</tag>
        </englishTags>
    </tags>
</animal>

=== LineVA/zoo/zoo/resources/species/lot1/pallasCat.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Manul</fr>
        <additionalFrenchNames>
            <name>Chat de Pallas</name>
        </additionalFrenchNames>
        <en>Manul</en>
        <additionalEnglishNames>
            <name>Palla's cat</name>
        </additionalEnglishNames>
        <scientific>Otocolopus manul</scientific>
    </names>
    <general>
        <uicn>2</uicn>
        <family>8</family>
        <continents>
            <continent>5</continent>
        </continents>
        <ecoregion>0</ecoregion>
        <breedingProgramme>1</breedingProgramme>
    </general>
    <documentation>
        <frenchWikipedia>https://fr.wikipedia.org/wiki/Palla's_cat</frenchWikipedia>
        <englishWikipedia>https://en.wikipedia.org/wiki/Chat-de-Pallas</englishWikipedia>
        <animalDiversity />
    </documentation>
    <reproduction>
        <femaleMaturity>12</femaleMaturity>
        <maleMaturity>12</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <gestationDuration>2</gestationDuration>
        <litterSize>4</litterSize>
        <leavingAge>5</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>294</femaleLifespan>
        <maleLifespan>294</maleLifespan>
    </lifespan>
    <territory>
        <territorySize>40</territorySize>
        <biomes>
            <biome>1</biome>
            <biome>2</biome>
            <biome>10</biome>
            <biome>13</biome>
        </biomes>
    </territory>
    <feeding>
        <quantity>0.360</quantity>
        <size>2</size>
        <diets>
            <diet>3</diet>
        </diets>
        <fastDays>1</fastDays>
    </feeding>
    <social>
        <groupSize>1</groupSize>
    </social>
</animal>

=== LineVA/zoo/zoo/resources/species/tmp/malayanTapir.xml
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Tapir de Malaisie</fr>
        <additionalFrenchNames>
            <name>Tapir d'Asie</name>
            <name>Tapir Ã  chabraques</name>
        </additionalFrenchNames>
        <en>Malayan tapir</en>
        <additionalEnglishNames>
            <name>Indian tapir</name>
        </additionalEnglishNames>
        <scientific>Tapirus indicus</scientific>
    </names>
    <general>
        <uicn>4</uicn>
        <family>27</family>
        <continents>
            <continent>5</continent>
        </continents>
        <ecoregion>0</ecoregion>
    </general>
    <documentation>
        <frenchWikipedia>https://fr.wikipedia.org/wiki/Tapir_de_Malaisie</frenchWikipedia>
        <englishWikipedia>https://en.wikipedia.org/wiki/Malayan_tapir</englishWikipedia>
        <animalDiversity></animalDiversity>
    </documentation>
    <reproduction>
        <femaleMaturity>32</femaleMaturity>
        <maleMaturity>36</maleMaturity>
        <gestationFrequency>0.5</gestationFrequency>
        <litterSize>1</litterSize>
        <leavingAge>0</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>300</femaleLifespan>
        <maleLifespan>300</maleLifespan>
    </lifespan>
    <territory>
        <biome>1</biome>
        <territorySize>36</territorySize>
    </territory>
    <feeding>
        <diet>8</diet>
        <quantity>15</quantity>
        <size>7</size>
    </feeding>
    <social>
        <groupSize>1</groupSize>
    </social>
</animal>

=== LineVA/zoo/zoo/resources/species/snowLeopard.xml
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Panthère des neiges</fr>
        <additionalFrenchNames>
            <name>Léopard des neiges</name>
            <name>Once</name>
            <name>Irbis</name>
        </additionalFrenchNames>
        <en>Snow leopard</en>
        <additionalEnglishNames>
            <name>Ounce</name>
        </additionalEnglishNames>
        <scientific>Uncia uncia</scientific>
    </names>
    <general>
        <uicn>4</uicn>
        <family>8</family>
        <continents>
            <continent>5</continent>
        </continents>
        <ecoregion>0</ecoregion>
    </general>
    <reproduction>
        <femaleMaturity>30</femaleMaturity>
        <maleMaturity>42</maleMaturity>
        <gestationFrequency>0.5</gestationFrequency>
        <litterSize>3</litterSize>
        <leavingAge>0</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>180</femaleLifespan>
        <maleLifespan>180</maleLifespan>
    </lifespan>
    <territory>
        <biome>10</biome>
        <territorySize>150</territorySize>
    </territory>
    <feeding>
        <diet>3</diet>
        <quantity>2.9</quantity>
        <size>4</size>
    </feeding>
    <social>
        <groupSize>1</groupSize>
    </social>
</animal>

=== LineVA/zoo/zoo/resources/species/yellowCheekedGibbon.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Gibbon à favoris roux</fr>
    <additionalFrenchNames>
        <name>Gibbon à joues jaunes</name>
    </additionalFrenchNames>
    <en>Yellow-cheeked gibbon</en>
    <additionalEnglishNames>
      <name>Golden-cheeked gibbon</name>
      <name>Yellow-cheeked crested gibbon</name>
      <name>Golden-cheeked crested gibbon</name>
      <name>Red-cheeked gibbon</name>
      <name>Buffed-cheeked gibbon</name>
      <name>gabriella's gibbon</name>
    </additionalEnglishNames>
    <scientific>Nomascus gabriellae</scientific>
  </names>
  <general>
    <uicn>4</uicn>
    <family>30</family>
    <continents>
      <continent>5</continent>
    </continents>
    <ecoregion>0</ecoregion>
    <breedingProgramme>1</breedingProgramme>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Nomascus_gabriellae</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Yellow-cheeked_gibbon</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>84</femaleMaturity>
    <maleMaturity>84</maleMaturity>
    <gestationFrequency>0.4</gestationFrequency>
    <litterSize>1</litterSize>
    <leavingAge>84</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>480</femaleLifespan>
    <maleLifespan>480</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>100</territorySize>
    <biomes>
      <biome>2</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>0.894</quantity>
    <size>2</size>
    <diets>
      <diet>5</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>2</groupSize>
  </social>
  <tags>
      <frenchTags>
          <tag>Mammifère</tag>
          <tag>Primate</tag>
          <tag>Singe</tag>
          <tag>Gibbon</tag>
      </frenchTags>
      <englishTags>
          <tag>Mammal</tag>
          <tag>Primate</tag>
          <tag>Monkey</tag>
          <tag>Gibbon</tag>
      </englishTags>
  </tags>
</animal>
