=== LineVA/zoo/zoo/resources/species/specie.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="animal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="names">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="fr"/>
                            <xs:element name="additionalFrenchNames">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="en"/>
                            <xs:element name="additionalEnglishNames">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="scientific"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="general">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="uicn"/>
                            <xs:element type="xs:string" name="family"/>
                            <xs:element name="continents">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="continent" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:integer" name="ecoregion"/>
                            <xs:element type="xs:string" name="breedingProgramme"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="documentation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="frenchWikipedia"/>
                            <xs:element type="xs:string" name="englishWikipedia"/>
                            <xs:element type="xs:string" name="animalDiversity"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="reproduction">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="femaleMaturity"/>
                            <xs:element type="xs:integer" name="maleMaturity"/>
                            <xs:element type="xs:decimal" name="gestationFrequency"/>
                            <xs:element type="xs:integer" name="gestationDuration" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:integer" name="litterSize"/>
                            <xs:element type="xs:integer" name="weaningAge" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:integer" name="leavingAge" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lifespan">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="femaleLifespan"/>
                            <xs:element type="xs:decimal" name="maleLifespan"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="territory">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="territorySize"/>
                            <xs:element name="biomes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="biome" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="feeding">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:decimal" name="quantity"/>
                            <xs:element type="xs:int" name="size"/>
                            <xs:element name="diets">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:integer" name="diet" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:int" name="fastDays" maxOccurs="1" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="social">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="groupSize"/>
                            <xs:element type="xs:string" name="territorial" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="activityPeriods" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="period" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="socialStructures" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="structure" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="maleParticipationInBreeding" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="isolationOfYoung" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tags" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="frenchTags">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="tag" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="englishTags">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="tag" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LineVA/zoo/zoo/resources/species/crownedLemur.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Lémur couronné</fr>
    <additionalFrenchNames />
    <en>Crowned lemur</en>
    <additionalEnglishNames />
    <scientific>Eulemur coronatus</scientific>
  </names>
  <general>
    <uicn>4</uicn>
    <family>10</family>
    <continents>
      <continent>1</continent>
    </continents>
    <ecoregion>0</ecoregion>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Lémur_couronné</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Crowned_lemur</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>20</femaleMaturity>
    <maleMaturity>20</maleMaturity>
    <gestationFrequency>1</gestationFrequency>
    <litterSize>2</litterSize>
    <leavingAge>6</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>240</femaleLifespan>
    <maleLifespan>240</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>80</territorySize>
    <biomes>
      <biome>2</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>0.140</quantity>
    <size>1</size>
    <diets>
      <diet>5</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>10</groupSize>
  </social>
</animal>

=== LineVA/zoo/zoo_1/resources/species/dianaMonkey.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Cercopithèque diane</fr>
        <additionalFrenchNames />
        <en>Diana monkey</en>
        <additionalEnglishNames />
        <scientific>Cercopithecus diana</scientific>
    </names>
    <general>
        <uicn>3</uicn>
        <family>31</family>
        <continents>
            <continent>1</continent>
        </continents>
        <ecoregion>0</ecoregion>
        <breedingProgramme>1</breedingProgramme>
    </general>
    <documentation>
        <frenchWikipedia>https://fr.wikipedia.org/wiki/Cercopithèque_diane</frenchWikipedia>
        <englishWikipedia>https://en.wikipedia.org/wiki/Diana_monkey</englishWikipedia>
        <animalDiversity />
    </documentation>
    <reproduction>
        <femaleMaturity>36</femaleMaturity>
        <maleMaturity>36</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>1</litterSize>
        <leavingAge>6</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>240</femaleLifespan>
        <maleLifespan>240</maleLifespan>
    </lifespan>
    <territory>
        <territorySize>120</territorySize>
        <biomes>
            <biome>1</biome>
        </biomes>
    </territory>
    <feeding>
        <quantity>0.786</quantity>
        <size>1</size>
        <diets>
            <diet>17</diet>
        </diets>
    </feeding>
    <social>
        <groupSize>15</groupSize>
    </social>
    <tags>
        <frenchTags>
            <tag>Mammifère</tag>
            <tag>Primate</tag>
            <tag>Singe</tag>
            <tag>Cercopithèque</tag>
            <tag>Cercopithecus</tag>
        </frenchTags>
        <englishTags>
            <tag>Mammal</tag>
            <tag>Primate</tag>
            <tag>Monkey</tag>
            <tag>Cercopithecus</tag>
        </englishTags>
    </tags>
</animal>

=== LineVA/zoo/zoo/resources/species/sumatranTiger.xml
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Tigre de Sumatra</fr>
        <additionalFrenchNames>
        </additionalFrenchNames>
        <en>Sumatran tiger</en>
        <additionalEnglishNames>
        </additionalEnglishNames>
        <scientific>Panthera tigris sumatrae</scientific>
    </names>
    <general>
        <uicn>4</uicn>
        <family>8</family>
        <continents>
            <continent>5</continent>
        </continents>
        <ecoregion>0</ecoregion>
    </general>
    <documentation>
        <frenchWikipedia></frenchWikipedia>
        <englishWikipedia></englishWikipedia>
        <animalDiversity></animalDiversity>
    </documentation>
    <reproduction>
        <femaleMaturity>30</femaleMaturity>
        <maleMaturity>42</maleMaturity>
        <gestationFrequency>0.3</gestationFrequency>
        <litterSize>3</litterSize>
        <leavingAge>0</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>180</femaleLifespan>
        <maleLifespan>180</maleLifespan>
    </lifespan>
    <territory>
        <biome>1</biome>
        <territorySize>200</territorySize>
    </territory>
    <feeding>
        <diet>3</diet>
        <quantity>3.0</quantity>
        <size>6</size>
    </feeding>
    <social>
        <groupSize>1</groupSize>
    </social>
</animal>

=== LineVA/zoo/zoo/resources/species/lot1/goeldisMarmoset.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Tamarin de Goeldi</fr>
    <additionalFrenchNames>
      <name>Callimico</name>
      <name>Tamarin sauteur</name>
    </additionalFrenchNames>
    <en>Goeldi's marmoset</en>
    <additionalEnglishNames>
      <name>Goeldi's monkey</name>
      <name>Goeldi's tamarin</name>
      <name>Spring tamarin</name>
      <name>Callimico</name>
    </additionalEnglishNames>
    <scientific>Callimico goeldii</scientific>
  </names>
  <general>
    <uicn>3</uicn>
    <family>26</family>
    <continents>
      <continent>2</continent>
    </continents>
    <ecoregion>0</ecoregion>
    <breedingProgramme>1</breedingProgramme>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Tamarin_de_Goeldi</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Goeldi%27s_marmoset</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>14</femaleMaturity>
    <maleMaturity>14</maleMaturity>
    <gestationFrequency>2</gestationFrequency>
    <gestationDuration>5</gestationDuration>
    <litterSize>1</litterSize>
    <weaningAge>3</weaningAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>144</femaleLifespan>
    <maleLifespan>144</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>48</territorySize>
    <biomes>
      <biome>1</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>0.108</quantity>
    <size>1</size>
    <diets>
      <diet>17</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>8</groupSize>
  </social>
    <tags>
        <frenchTags>
            <tag>Mammif√®re</tag>
            <tag>Primate</tag>
            <tag>Singe</tag>
            <tag>Ouistiti</tag>
            <tag>Goeldi</tag>
            <tag>Sauteur</tag>
            <tag></tag>
        </frenchTags>
        <englishTags>
            <tag>Mammal</tag>
            <tag>Primate</tag>
            <tag>Monkey</tag>
            <tag>Geoffroy</tag>
            <tag>Marmoset</tag>
            <tag>Jumped</tag>
            <tag></tag>
        </englishTags>
    </tags>
</animal>

=== LineVA/zoo/zoo_1/resources/species/hippopotamus.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>Hippopotame</fr>
        <additionalFrenchNames>
            <name>Hippopotame amphibie</name>
        </additionalFrenchNames>
        <en>HIppopotamus</en>
        <additionalEnglishNames>
            <name>Hippo</name>
        </additionalEnglishNames>
        <scientific>Hippopotamus amphibius</scientific>
    </names>
    <general>
        <uicn>3</uicn>
        <family>35</family>
        <continents>
            <continent>1</continent>
        </continents>
        <ecoregion>0</ecoregion>
        <breedingProgramme>2</breedingProgramme>
    </general>
    <documentation>
        <frenchWikipedia>https://fr.wikipedia.org/wiki/Hippopotamus_amphibius</frenchWikipedia>
        <englishWikipedia>https://en.wikipedia.org/wiki/Hippopotamus</englishWikipedia>
        <animalDiversity />
    </documentation>
    <reproduction>
        <femaleMaturity>43</femaleMaturity>
        <maleMaturity>43</maleMaturity>
        <gestationFrequency>0.5</gestationFrequency>
        <litterSize>1</litterSize>
        <weaningAge>12</weaningAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>540</femaleLifespan>
        <maleLifespan>540</maleLifespan>
    </lifespan>
    <territory>
        <territorySize>1500</territorySize>
        <biomes>
            <biome>1</biome>
            <biome>7</biome>
            <biome>13</biome>
        </biomes>
    </territory>
    <feeding>
        <quantity>20.0</quantity>
        <size>8</size>
        <diets>
            <diet>21</diet>
        </diets>
    </feeding>
    <social>
        <groupSize>10</groupSize>
    </social>
    <tags>
        <frenchTags>
            <tag>Mammif√®re</tag>
            <tag>Hippopotame</tag>
            <tag>Amphibie</tag>
        </frenchTags>
        <englishTags>
            <tag>Mammal</tag>
            <tag>Hippopotamus</tag>
            <tag>Hippo</tag>
        </englishTags>
    </tags>
</animal>

=== LineVA/zoo/zoo/test/zoo/paddock/speciesForListAnimalTest/zebre2.xml
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
    <names>
        <fr>ZEBRE2_fr</fr>
        <en>ZEBRE2_en</en>
        <scientific>ZEBRE2</scientific>
    </names>
    <general>
        <uicn>2</uicn>
        <family>2</family>
        <continents>
            <continent>2</continent>
        </continents>
        <ecoregion>0</ecoregion>
    </general>
    <reproduction>
        <femaleMaturity>66</femaleMaturity>
        <maleMaturity>42</maleMaturity>
        <gestationFrequency>0</gestationFrequency>
        <litterSize>1</litterSize>
        <leavingAge>22</leavingAge>
    </reproduction>
    <lifespan>
        <femaleLifespan>240</femaleLifespan>
        <maleLifespan>240</maleLifespan>
    </lifespan>
    <territory>
        <biome>13</biome>
        <territorySize>9.4</territorySize>
    </territory>
    <feeding>
        <diet>2</diet>
        <quantity>5.7</quantity>
        <size>2</size>
    </feeding>
    <social>
        <groupSize>10</groupSize>
    </social>
</animal>

=== LineVA/zoo/zoo_1/resources/atmp/backUpSpecies/goeldisMarmoset.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Tamarin de Goeldi</fr>
    <additionalFrenchNames>
      <name>Callimico</name>
      <name>Tamarin sauteur</name>
    </additionalFrenchNames>
    <en>Goeldi's marmoset</en>
    <additionalEnglishNames>
      <name>Goeldi's monkey</name>
      <name>Goeldi's tamarin</name>
      <name>Spring tamarin</name>
      <name>Callimico</name>
    </additionalEnglishNames>
    <scientific>Callimico goeldi</scientific>
  </names>
  <general>
    <uicn>3</uicn>
    <family>26</family>
    <continents>
      <continent>2</continent>
    </continents>
    <ecoregion>0</ecoregion>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Tamarin_de_Goeldi</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/Goeldi%27s_marmoset</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>14</femaleMaturity>
    <maleMaturity>14</maleMaturity>
    <gestationFrequency>2</gestationFrequency>
    <litterSize>1</litterSize>
    <leavingAge>0</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>144</femaleLifespan>
    <maleLifespan>144</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>48</territorySize>
    <biomes>
      <biome>1</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>0.108</quantity>
    <size>1</size>
    <diets>
      <diet>17</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>8</groupSize>
  </social>
</animal>

=== LineVA/zoo/zoo/resources/species/redBelliedMonkey.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./resources/species/specie.xsd">
  <names>
    <fr>Hocheur à ventre roux</fr>
    <additionalFrenchNames>
      <name>Hocheur à ventre rouge</name>
      <name>Singe à ventre rouge</name>
    </additionalFrenchNames>
    <en>Red-bellied monkey</en>
    <additionalEnglishNames>
      <name>White-throated guenon</name>
      <name>Red-bellied guenon</name>
    </additionalEnglishNames>
    <scientific>Cercopithecus erythrogaster</scientific>
  </names>
  <general>
    <uicn>3</uicn>
    <family>31</family>
    <continents>
      <continent>1</continent>
    </continents>
    <ecoregion>0</ecoregion>
    <breedingProgramme>0</breedingProgramme>
  </general>
  <documentation>
    <frenchWikipedia>https://fr.wikipedia.org/wiki/Cercopithecus_erythrogaster</frenchWikipedia>
    <englishWikipedia>https://en.wikipedia.org/wiki/White-throated_guenon</englishWikipedia>
    <animalDiversity />
  </documentation>
  <reproduction>
    <femaleMaturity>36</femaleMaturity>
    <maleMaturity>36</maleMaturity>
    <gestationFrequency>1</gestationFrequency>
    <litterSize>1</litterSize>
    <leavingAge>6</leavingAge>
  </reproduction>
  <lifespan>
    <femaleLifespan>230</femaleLifespan>
    <maleLifespan>230</maleLifespan>
  </lifespan>
  <territory>
    <territorySize>80</territorySize>
    <biomes>
      <biome>1</biome>
    </biomes>
  </territory>
  <feeding>
    <quantity>0.708</quantity>
    <size>1</size>
    <diets>
      <diet>17</diet>
    </diets>
  </feeding>
  <social>
    <groupSize>10</groupSize>
  </social>
</animal>
