=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="animal">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="names">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="fr"/>
              <xs:element type="xs:string" name="en"/>
              <xs:element type="xs:string" name="scientific"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="reproduction">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="femaleMaturity"/>
              <xs:element type="xs:int" name="maleMaturity"/>
              <xs:element type="xs:decimal" name="gestationFrequency"/>
              <xs:element type="xs:int" name="litterSize"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="lifespan">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="femaleLifespan"/>
              <xs:element type="xs:int" name="maleLifeSpan"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/polarBear.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Ours blanc</fr>
        <en>Polar bear</en>
        <scientific>Ursus maritimus</scientific>
    </names>
    <reproduction>
        <femaleMaturity>66</femaleMaturity>
        <maleMaturity>66</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>2</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>330</femaleLifespan>
        <maleLifeSpan>330</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/smoothCoatedOtter.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Loutre d'Asie</fr>
        <en>Smooth-coated otter</en>
        <scientific>Lutrogale perspicillata</scientific>
    </names>
    <reproduction>
        <femaleMaturity>24</femaleMaturity>
        <maleMaturity>24</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>5</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>84</femaleLifespan>
        <maleLifeSpan>84</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/serval.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Serval</fr>
        <en>Serval</en>
        <scientific>Leptailurus serval</scientific>
    </names>
    <reproduction>
        <femaleMaturity>27</femaleMaturity>
        <maleMaturity>???</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>3</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>120</femaleLifespan>
        <maleLifeSpan>120</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/demoiselleCrane.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Grue demoiselle</fr>
        <en>Demoiselle crane</en>
        <scientific>Anthropoides virgo</scientific>
    </names>
    <reproduction>
        <femaleMaturity>72</femaleMaturity>
        <maleMaturity>72</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>2</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>324</femaleLifespan>
        <maleLifeSpan>324</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/ringTailedLemur.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Maki catta</fr>
        <en>Ring-tailed lemur</en>
        <scientific>Lemur catta</scientific>
    </names>
    <reproduction>
        <femaleMaturity>36</femaleMaturity>
        <maleMaturity>42</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>1</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>324</femaleLifespan>
        <maleLifeSpan>324</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/redRuffedLemur.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Vari roux</fr>
        <en>Red ruffed lemur</en>
        <scientific>Varecia rubra</scientific>
    </names>
    <reproduction>
        <femaleMaturity>24</femaleMaturity>
        <maleMaturity>???</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>3</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>240</femaleLifespan>
        <maleLifeSpan>240</maleLifeSpan>
    </lifespan>
</animal>
