=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="animal">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="names">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="fr"/>
              <xs:element type="xs:string" name="en"/>
              <xs:element type="xs:string" name="scientific"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="reproduction">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="femaleMaturity"/>
              <xs:element type="xs:int" name="maleMaturity"/>
              <xs:element type="xs:decimal" name="gestationFrequency"/>
              <xs:element type="xs:int" name="litterSize"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="lifespan">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="femaleLifespan"/>
              <xs:element type="xs:int" name="maleLifeSpan"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/lama.xml
<?xml version="1.0" encoding="UTF-8"?>

<animal
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd'>
    <names>
        <fr>Lama</fr>
       <en>Lama</en>
        <scientific>Lama glama</scientific>
    </names>
    <reproduction>
        <femaleMaturity>42</femaleMaturity>
        <maleMaturity>42</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>1</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>240</femaleLifespan>
        <maleLifeSpan>240</maleLifeSpan>
    </lifespan>

</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/emu.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Emeu australien</fr>
        <en>Emu</en>
        <scientific>Dromaius novaehollandiae</scientific>
    </names>
    <reproduction>
        <femaleMaturity>19</femaleMaturity>
        <maleMaturity>19</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>10</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>84</femaleLifespan>
        <maleLifeSpan>84</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/tocoToucan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<animal
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd'>
    <names>
        <fr>Toucan toco</fr>
       <en>Toco toucan</en>
        <scientific>Ramphastos toco</scientific>
    </names>
    <reproduction>
        <femaleMaturity>42</femaleMaturity>
        <maleMaturity>42</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>3</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>256</femaleLifespan>
        <maleLifeSpan>256</maleLifeSpan>
    </lifespan>

</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/chimpanze.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Chimpanz√© commun</fr>
        <en>Chimpanze</en>
        <scientific>Pan troglodytes</scientific>
    </names>
    <reproduction>
        <femaleMaturity>78</femaleMaturity>
        <maleMaturity>78</maleMaturity>
        <gestationFrequency>???</gestationFrequency>
        <litterSize>1</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>600</femaleLifespan>
        <maleLifeSpan>600</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/blackandWhiteRuffedLemur.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Vari noir et blanc</fr>
        <en>Black and white ruffed lemur</en>
        <scientific>Varecia variegata</scientific>
    </names>
    <reproduction>
        <femaleMaturity>20</femaleMaturity>
        <maleMaturity>20</maleMaturity>
        <gestationFrequency>1</gestationFrequency>
        <litterSize>3</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>228</femaleLifespan>
        <maleLifeSpan>228</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/bonobo.xml
<animal xsi:noNamespaceSchemaLocation="file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd">
    <names>
        <fr>Bonobo</fr>
        <en>Bonobo</en>
        <scientific>Pan satyrus paniscus</scientific>
    </names>
    <reproduction>
        <femaleMaturity>168</femaleMaturity>
        <maleMaturity>168</maleMaturity>
        <gestationFrequency>0.2</gestationFrequency>
        <litterSize>1</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>240</femaleLifespan>
        <maleLifeSpan>240</maleLifeSpan>
    </lifespan>
</animal>

=== LineVA/zoo/zoo/src/zoo/animal/specie/resourceSpecie/chileanFlamingo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<animal
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd'>
    <names>
        <fr>Flamand rose du Chili</fr>
       <en>Chilean flamingo</en>
        <scientific>Phoenicopterus chilensis</scientific>
    </names>
    <reproduction>
        <femaleMaturity>72</femaleMaturity>
        <maleMaturity>72</maleMaturity>
        <gestationFrequency>0.75</gestationFrequency>
        <litterSize>1</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>540</femaleLifespan>
        <maleLifeSpan>540</maleLifeSpan>
    </lifespan>

</animal>

=== LineVA/zoo/zoo/test/zoo/zoo/resourceSpeciesTest/blueKangoroo.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/doyenm/Documents/Projets/zoo/zoo/src/zoo/animal/specie/resourceSpecie/model.xsd'>
    <names>
        <fr>Kangourou bleu</fr>
        <en>Blue kangoroo</en>
        <scientific>Macropus rufus</scientific>
    </names>
    <reproduction>
        <femaleMaturity>1</femaleMaturity>
        <maleMaturity>2</maleMaturity>
        <gestationFrequency>3.0</gestationFrequency>
        <litterSize>4</litterSize>
    </reproduction>
    <lifespan>
        <femaleLifespan>5</femaleLifespan>
        <maleLifeSpan>6</maleLifeSpan>
    </lifespan>
</animal>
